# Generated by Django 3.2.8 on 2021-12-02 08:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
